### ISSUE TITLE
[New Service] Braintree

### ISSUE THREAD

**Issue by clarkeash** [clarkeash/shield#4]
Docs: https://developers.braintreepayments.com/guides/webhooks/parse/php

I would prefer to not pull in any dependencies for this.

**Comment by peppeocchi** [comment]
Hi @clarkeash thanks for this great package.

I understand you don't want to pull any dependency, but if someone wants to use the braintree shield that means the Braintree SDK is already loaded.

My suggestion would be to use the Braintree SDK anyway (I don't like the idea of trying to replicate the functions used to [generate the signature](https://github.com/braintree/braintree_php/blob/master/lib/Braintree/Digest.php#L10)), add it as a require-dev dependency (for testing purposes) and add it as a [suggested package](https://getcomposer.org/doc/04-schema.md#suggest) in composer.

I'll send a PR shortly with what I just said, feel free to reject it if want to go for a different solution.

**Comment by clarkeash** [comment]
Thats a fair point. I will do a code review before I merge, but that will probably be at the weekend.
